# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71f735162fe2869e684a78dc010937ae3cf2bb8463e9e57ca2ed225225a7674a150bce416f87ebfce0f5fe5e590c991ff0375a116b6798b6ac7604bb71a403bd

test:
  secret_key_base: 7c6b1da22bce523b7c3692dd28e5e1a7944fd036d71ea90d80b7e92a7652f82017085ed58b2bc324d7c79a5a6bdb4a335a2b5ccec55b4a6541f8dbb643ff5ef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
